# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EazybiCli < Formula
  desc "Command-line interface for eazyBI"
  homepage "https://eazybi.com"
  version "0.3.7"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://eazybi.com/system/downloads/eazybi-cli-0.3.7-darwin-amd64.tar.gz"
      sha256 "055f90824e0a4f5b33573a900e1c40f5feb5163d28f3a1c8fa9a9ebfd5d15251"

      define_method(:install) do
        bin.install "eazybi"
        generate_completions_from_executable(bin/"eazybi", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://eazybi.com/system/downloads/eazybi-cli-0.3.7-darwin-arm64.tar.gz"
      sha256 "036122555016cbd1a2c044b5192ee6d11283d32761564f46af70ad5bb76b1f01"

      define_method(:install) do
        bin.install "eazybi"
        generate_completions_from_executable(bin/"eazybi", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://eazybi.com/system/downloads/eazybi-cli-0.3.7-linux-amd64.tar.gz"
      sha256 "d9e875b8eb272dad8a1de1f6400ad3c76dc7d142af4a68042dbf7ff9534f5ba3"
      define_method(:install) do
        bin.install "eazybi"
        generate_completions_from_executable(bin/"eazybi", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://eazybi.com/system/downloads/eazybi-cli-0.3.7-linux-arm64.tar.gz"
      sha256 "0b6d783c8d2954d3ec47e09abf420f463007e7cb0e4c89fa4db008cf303a46e5"
      define_method(:install) do
        bin.install "eazybi"
        generate_completions_from_executable(bin/"eazybi", "completion")
      end
    end
  end

  test do
    assert_match "eazybi", shell_output("#{bin}/eazybi --version")
  end
end
