# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class EazybiCli < Formula
  desc "Command-line interface for eazyBI"
  homepage "https://github.com/eazybi/eazybi_cli"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eazybi/eazybi_cli/releases/download/v0.1.0/eazybi_0.1.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7303dd8fa442b5b3099b2f745ca9bd5b973c4af39f1acd0e0b63d93ce8796fbd"

      define_method(:install) do
        bin.install "eazybi"
        generate_completions_from_executable(bin/"eazybi", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eazybi/eazybi_cli/releases/download/v0.1.0/eazybi_0.1.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f0854591c5761ea54b3cd19c7d57b9bb9ba1159e7737027f4618ea4524ca265c"

      define_method(:install) do
        bin.install "eazybi"
        generate_completions_from_executable(bin/"eazybi", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eazybi/eazybi_cli/releases/download/v0.1.0/eazybi_0.1.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8500be2135d3094504e7196266753e5e587b32c7bc7480799c051be98ac3ff38"
      define_method(:install) do
        bin.install "eazybi"
        generate_completions_from_executable(bin/"eazybi", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eazybi/eazybi_cli/releases/download/v0.1.0/eazybi_0.1.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "87d83099a33090dc5ee9bcbe1e76b1f59fbf3e23cba95dc2a76a5d8319e04719"
      define_method(:install) do
        bin.install "eazybi"
        generate_completions_from_executable(bin/"eazybi", "completion")
      end
    end
  end

  test do
    assert_match "eazybi", shell_output("#{bin}/eazybi --version")
  end
end
