# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EazybiCli < Formula
  desc "Command-line interface for eazyBI"
  homepage "https://eazybi.com"
  version "0.3.3"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://eazybi.com/system/downloads/eazybi-cli-0.3.3-darwin-amd64.tar.gz"
      sha256 "a1224295a1e9d879b2af7e2b1ff700f15a1be00f2a8d93bb3b7eb783faa93288"

      define_method(:install) do
        bin.install "eazybi"
        generate_completions_from_executable(bin/"eazybi", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://eazybi.com/system/downloads/eazybi-cli-0.3.3-darwin-arm64.tar.gz"
      sha256 "02979d47c00ec5a82b0e2019e7671a2decbd74e082ee73fc38612bc3b18e06e4"

      define_method(:install) do
        bin.install "eazybi"
        generate_completions_from_executable(bin/"eazybi", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://eazybi.com/system/downloads/eazybi-cli-0.3.3-linux-amd64.tar.gz"
      sha256 "c4a66b97de594dc0e0575a8d0e6a179e5455fbd992c92fde695467e68e24c3c6"
      define_method(:install) do
        bin.install "eazybi"
        generate_completions_from_executable(bin/"eazybi", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://eazybi.com/system/downloads/eazybi-cli-0.3.3-linux-arm64.tar.gz"
      sha256 "9225effdb614f1106e5cba85b02629a31a1d9ebdcd79b5156b97865e439bfbee"
      define_method(:install) do
        bin.install "eazybi"
        generate_completions_from_executable(bin/"eazybi", "completion")
      end
    end
  end

  test do
    assert_match "eazybi", shell_output("#{bin}/eazybi --version")
  end
end
